apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hpavalidator.fullname" . }}
  labels:
    {{- include "hpavalidator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hpavalidator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hpavalidator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hpavalidator.serviceAccountName" . }}
      containers:
        - name: hpavalidator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--metrics-bind-address=:8080"
            - "--health-probe-bind-address=:8081"
          ports:
            - name: metrics
              containerPort: 8080
            - name: healthz
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
